; WORLD.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 1
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

SECTION "Tiles", ROM0

; Start of tile array.
WorldTiles::
	DB $00,$00,$10,$10,$18,$18,$FC,$FC
	DB $FE,$FE,$FC,$FC,$18,$18,$10,$10
	DB $7E,$FF,$7E,$FF,$BD,$7E,$C3,$3C
	DB $C3,$3C,$BD,$7E,$76,$FF,$76,$FF

; End of WORLD.Z80
